# Notes:
#   - Minimal appveyor.yml file is an empty file. All sections are optional.
#   - Indent each level of configuration with 2 spaces. Do not use tabs!
#   - All section names are case-sensitive.
#   - Section names should be unique on each level.

#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 1.5.{build}

# branches to build
branches:
  # whitelist
  only:
    - master

  # blacklist
  except:
    - gh-pages

# Maximum number of concurrent jobs for the project
max_jobs: 1

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Build worker image (VM template)
os: Visual Studio 2019

#---------------------------------#
#       build configuration       #
#---------------------------------#

install:
  - cmd: git submodule update --init --recursive
  - cmd: msbuild /version

# build Configuration, i.e. Debug, Release, etc.
configuration: Release

build_script:
  - ps: (Get-Content  C:\projects\vsmr\vSMR\SMRPlugin.hpp).replace('@appveyor_build', $Env:appveyor_build_version) | Set-Content  C:\projects\vsmr\vSMR\SMRPlugin.hpp
  - cmd: msbuild "C:\projects\vsmr\vSMR.sln" /m /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

after_build:
  - cmd: mkdir vSMR-nightly
  - cmd: cp Release\vSMR.dll vSMR-nightly\
  - cmd: cp vSMR\vSMR_Profiles.json vSMR-nightly\
  - cmd: 7z a vSMR-nightly.zip %APPVEYOR_BUILD_FOLDER%\vSMR-nightly\

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:
  - path: vSMR-nightly.zip
